### ISSUE TITLE
name history

### ISSUE THREAD

**Issue by GalacticArcanum** [ausFort/dCommander#4]
A command to track previous names of name changers. So that the result is a notification to perm holders that Player_newName is back online and that player's old name was in fact "Player_oldName".

Maybe even that Player has multiple previous names, "player_oldName, player_oldName2"

**Comment by Fortifier42** [comment]
I have added name history to the player storage, however has no purpose as of yet.

**Comment by Fortifier42** [comment]
This has now been completed and have added seen names command :)
