### ISSUE TITLE
Need /seen command..

### ISSUE THREAD

**Issue by Fortifier42** [ausFort/dCommander#5]
Could return things like -
- Last seen IP
- Last seen time
- Location
- Health
- Ban status (thanks to new tags, this is possible)

**Comment by GalacticArcanum** [comment]
On the "Last seen IP" make that portion permission based as well. So that only certain ppl can view IP

**Comment by Fortifier42** [comment]
/seen command can be used for any players.
Anyone can see when they were last online, their health and if they are banned.
Admins can see that, along with when they were banned, why they were banned and also the expiry (if it expires).
