### ISSUE TITLE
lockdown pin pad with 6 digit input

### ISSUE THREAD

**Issue by GalacticArcanum** [ausFort/dCommander#6]
Some users have trolls for siblings or roomates or even spouses.

Those users can have an opt-in security pad (crafting table) pop up upon joining the server that blocks the users ability to play. If you put the wrong pin number in it just restarts the script.

When you put in the correct 6 digit pin number access is granted to the server and regular joining systems are engaged.

Also needs easy opt-out and pin changing system.

**Comment by mcmonkey4eva** [comment]
Sounds like you want a whole separate plugin/script, not a feature of dEssCloner.

**Comment by Fortifier42** [comment]
Yeah this is completely separate to... anything related to this..
but Thanks mcmonkey for your support :|
